---
- hosts: webservers
  tasks:
  




  - name: wordpressi jaoks andmebaasi loomine
    mysql_db:
      name: wpdatabase
      state: present



  - name: wordpressi kasutaja loomine. nimi wpuser password qwerty
    mysql_user:
      name: wpuser
      password: qwerty
      priv: 'wpdatabase.*:ALL,GRANT'
      state: present
      check_implicit_admin: yes



  - name: mysql restart
    service: name=mysql state=restarted

  - name: wordpress allalaadimine
    unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: /var/www/html/
      remote_src: yes

  - name: Wordpressi omaniku vahetamine wwwdataks
    file:
      path: /var/www/html/wordpress/
      state: directory
      recurse: yes
      owner: www-data




  - name: configfaili kopeerimine
    command: cp /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php

  - name: parooli muudatused
    lineinfile: dest=/var/www/html/wordpress/wp-config.php regexp="'password_here'" line="define( 'DB_PASSWORD', 'qwerty' );"


  - name: Username muudatused
    lineinfile: dest=/var/www/html/wordpress/wp-config.php regexp="'username_here'" line="define( 'DB_USER', 'wpuser' );"


  - name: DB muutmine
    lineinfile: dest=/var/www/html/wordpress/wp-config.php regexp="'database_name_here'" line="define( 'DB_NAME', 'wpdatabase' );"

